//! GENERATED by scripts/gen-dtape-traps.py. Do not edit.
//!
//! The Rust half of `duct-tape/src/traps.c` (#71): the 29 wrappers that
//! `DSERVER_DTAPE_DEFS` expands to in the C. Each packs its scalar arguments into an
//! XNU trap-args struct and calls the trap.
//!
//! Generated from the SAME table the C uses, the expansion of that macro in the built
//! `darlingserver/rpc.internal.h`, so the two cannot disagree. Writing them by hand
//! would mean transcribing 29 signatures and about 90 field assignments, and a swapped
//! field between two same-typed arguments would compile, link and return the wrong
//! answer.

#![allow(clippy::too_many_arguments)]

use crate::bindings::*;

#[no_mangle]
pub unsafe extern "C" fn dtape_mach_msg_overwrite(msg: u64, option: i32, send_size: u32, rcv_size: u32, rcv_name: u32, timeout: u32, priority: u32, rcv_msg: u64) -> ::std::os::raw::c_int {
    let mut args: mach_msg_overwrite_trap_args = ::std::mem::zeroed();
    args.msg = msg as _;
    args.option = option as _;
    args.send_size = send_size as _;
    args.rcv_size = rcv_size as _;
    args.rcv_name = rcv_name as _;
    args.timeout = timeout as _;
    args.priority = priority as _;
    args.rcv_msg = rcv_msg as _;
    mach_msg_overwrite_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_mach_port_deallocate(target: u32, name: u32) -> ::std::os::raw::c_int {
    let mut args: _kernelrpc_mach_port_deallocate_args = ::std::mem::zeroed();
    args.target = target as _;
    args.name = name as _;
    _kernelrpc_mach_port_deallocate_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_mach_port_allocate(target: u32, right: i32, name: u64) -> ::std::os::raw::c_int {
    let mut args: _kernelrpc_mach_port_allocate_args = ::std::mem::zeroed();
    args.target = target as _;
    args.right = right as _;
    args.name = name as _;
    _kernelrpc_mach_port_allocate_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_mach_port_mod_refs(target: u32, name: u32, right: i32, delta: i32) -> ::std::os::raw::c_int {
    let mut args: _kernelrpc_mach_port_mod_refs_args = ::std::mem::zeroed();
    args.target = target as _;
    args.name = name as _;
    args.right = right as _;
    args.delta = delta as _;
    _kernelrpc_mach_port_mod_refs_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_mach_port_move_member(target: u32, member: u32, after: u32) -> ::std::os::raw::c_int {
    let mut args: _kernelrpc_mach_port_move_member_args = ::std::mem::zeroed();
    args.target = target as _;
    args.member = member as _;
    args.after = after as _;
    _kernelrpc_mach_port_move_member_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_mach_port_insert_right(target: u32, name: u32, poly: u32, polyPoly: i32) -> ::std::os::raw::c_int {
    let mut args: _kernelrpc_mach_port_insert_right_args = ::std::mem::zeroed();
    args.target = target as _;
    args.name = name as _;
    args.poly = poly as _;
    args.polyPoly = polyPoly as _;
    _kernelrpc_mach_port_insert_right_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_mach_port_insert_member(target: u32, name: u32, pset: u32) -> ::std::os::raw::c_int {
    let mut args: _kernelrpc_mach_port_insert_member_args = ::std::mem::zeroed();
    args.target = target as _;
    args.name = name as _;
    args.pset = pset as _;
    _kernelrpc_mach_port_insert_member_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_mach_port_extract_member(target: u32, name: u32, pset: u32) -> ::std::os::raw::c_int {
    let mut args: _kernelrpc_mach_port_extract_member_args = ::std::mem::zeroed();
    args.target = target as _;
    args.name = name as _;
    args.pset = pset as _;
    _kernelrpc_mach_port_extract_member_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_mach_port_construct(target: u32, options: u64, context: u64, name: u64) -> ::std::os::raw::c_int {
    let mut args: _kernelrpc_mach_port_construct_args = ::std::mem::zeroed();
    args.target = target as _;
    args.options = options as _;
    args.context = context as _;
    args.name = name as _;
    _kernelrpc_mach_port_construct_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_mach_port_destruct(target: u32, name: u32, srdelta: i32, guard: u64) -> ::std::os::raw::c_int {
    let mut args: _kernelrpc_mach_port_destruct_args = ::std::mem::zeroed();
    args.target = target as _;
    args.name = name as _;
    args.srdelta = srdelta as _;
    args.guard = guard as _;
    _kernelrpc_mach_port_destruct_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_mach_port_guard(target: u32, name: u32, guard: u64, strict: bool) -> ::std::os::raw::c_int {
    let mut args: _kernelrpc_mach_port_guard_args = ::std::mem::zeroed();
    args.target = target as _;
    args.name = name as _;
    args.guard = guard as _;
    args.strict = strict as _;
    _kernelrpc_mach_port_guard_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_mach_port_unguard(target: u32, name: u32, guard: u64) -> ::std::os::raw::c_int {
    let mut args: _kernelrpc_mach_port_unguard_args = ::std::mem::zeroed();
    args.target = target as _;
    args.name = name as _;
    args.guard = guard as _;
    _kernelrpc_mach_port_unguard_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_mach_port_request_notification(target: u32, name: u32, msgid: i32, sync: u32, notify: u32, notifyPoly: u32, previous: u64) -> ::std::os::raw::c_int {
    let mut args: _kernelrpc_mach_port_request_notification_args = ::std::mem::zeroed();
    args.target = target as _;
    args.name = name as _;
    args.msgid = msgid as _;
    args.sync = sync as _;
    args.notify = notify as _;
    args.notifyPoly = notifyPoly as _;
    args.previous = previous as _;
    _kernelrpc_mach_port_request_notification_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_mach_port_get_attributes(target: u32, name: u32, flavor: i32, info: u64, count: u64) -> ::std::os::raw::c_int {
    let mut args: _kernelrpc_mach_port_get_attributes_args = ::std::mem::zeroed();
    args.target = target as _;
    args.name = name as _;
    args.flavor = flavor as _;
    args.info = info as _;
    args.count = count as _;
    _kernelrpc_mach_port_get_attributes_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_mach_port_type(target: u32, name: u32, ptype: u64) -> ::std::os::raw::c_int {
    let mut args: _kernelrpc_mach_port_type_args = ::std::mem::zeroed();
    args.target = target as _;
    args.name = name as _;
    args.ptype = ptype as _;
    _kernelrpc_mach_port_type_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_task_for_pid(target_tport: u32, pid: i32, t: u64) -> ::std::os::raw::c_int {
    let mut args: task_for_pid_args = ::std::mem::zeroed();
    args.target_tport = target_tport as _;
    args.pid = pid as _;
    args.t = t as _;
    task_for_pid(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_task_name_for_pid(target_tport: u32, pid: i32, t: u64) -> ::std::os::raw::c_int {
    let mut args: task_name_for_pid_args = ::std::mem::zeroed();
    args.target_tport = target_tport as _;
    args.pid = pid as _;
    args.t = t as _;
    task_name_for_pid(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_pid_for_task(t: u32, pid: u64) -> ::std::os::raw::c_int {
    let mut args: pid_for_task_args = ::std::mem::zeroed();
    args.t = t as _;
    args.pid = pid as _;
    pid_for_task(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_mach_vm_allocate(target: u32, addr: u64, size: u64, flags: i32) -> ::std::os::raw::c_int {
    let mut args: _kernelrpc_mach_vm_allocate_trap_args = ::std::mem::zeroed();
    args.target = target as _;
    args.addr = addr as _;
    args.size = size as _;
    args.flags = flags as _;
    _kernelrpc_mach_vm_allocate_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_mach_vm_deallocate(target: u32, address: u64, size: u64) -> ::std::os::raw::c_int {
    let mut args: _kernelrpc_mach_vm_deallocate_args = ::std::mem::zeroed();
    args.target = target as _;
    args.address = address as _;
    args.size = size as _;
    _kernelrpc_mach_vm_deallocate_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_semaphore_signal(signal_name: u32) -> ::std::os::raw::c_int {
    let mut args: semaphore_signal_trap_args = ::std::mem::zeroed();
    args.signal_name = signal_name as _;
    semaphore_signal_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_semaphore_signal_all(signal_name: u32) -> ::std::os::raw::c_int {
    let mut args: semaphore_signal_all_trap_args = ::std::mem::zeroed();
    args.signal_name = signal_name as _;
    semaphore_signal_all_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_semaphore_wait(wait_name: u32) -> ::std::os::raw::c_int {
    let mut args: semaphore_wait_trap_args = ::std::mem::zeroed();
    args.wait_name = wait_name as _;
    semaphore_wait_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_semaphore_wait_signal(wait_name: u32, signal_name: u32) -> ::std::os::raw::c_int {
    let mut args: semaphore_wait_signal_trap_args = ::std::mem::zeroed();
    args.wait_name = wait_name as _;
    args.signal_name = signal_name as _;
    semaphore_wait_signal_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_semaphore_timedwait(wait_name: u32, sec: u32, nsec: u32) -> ::std::os::raw::c_int {
    let mut args: semaphore_timedwait_trap_args = ::std::mem::zeroed();
    args.wait_name = wait_name as _;
    args.sec = sec as _;
    args.nsec = nsec as _;
    semaphore_timedwait_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_semaphore_timedwait_signal(wait_name: u32, signal_name: u32, sec: u32, nsec: u32) -> ::std::os::raw::c_int {
    let mut args: semaphore_timedwait_signal_trap_args = ::std::mem::zeroed();
    args.wait_name = wait_name as _;
    args.signal_name = signal_name as _;
    args.sec = sec as _;
    args.nsec = nsec as _;
    semaphore_timedwait_signal_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_mk_timer_destroy(name: u32) -> ::std::os::raw::c_int {
    let mut args: mk_timer_destroy_trap_args = ::std::mem::zeroed();
    args.name = name as _;
    mk_timer_destroy_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_mk_timer_arm(name: u32, expire_time: u64) -> ::std::os::raw::c_int {
    let mut args: mk_timer_arm_trap_args = ::std::mem::zeroed();
    args.name = name as _;
    args.expire_time = expire_time as _;
    mk_timer_arm_trap(&mut args)
}

#[no_mangle]
pub unsafe extern "C" fn dtape_mk_timer_cancel(name: u32, result_time: u64) -> ::std::os::raw::c_int {
    let mut args: mk_timer_cancel_trap_args = ::std::mem::zeroed();
    args.name = name as _;
    args.result_time = result_time as _;
    mk_timer_cancel_trap(&mut args)
}
