#!/bin/sh
set -e

DATE=$(date +%Y%m%d)
rm -f debian/changelog
DISTRO=${DEB_DISTRO:-"$(lsb_release -cs)"}
VERSION=0.1.${DATE}~${DISTRO}
EDITOR=true NAME="Darling build server" EMAIL=${DEB_EMAIL:-noreply@ciderhq.org} dch -u low -v ${VERSION} --create --distribution ${DISTRO} --package cider "Daily build"

ARG='-S'
if [ -e "../cider_${VERSION}.orig.tar.xz" ]; then
rm ../cider_${VERSION}.orig.tar.xz
fi
tar -cJf ../cider_${VERSION}.orig.tar.xz .

debuild --no-lintian -us -uc -S ${ARG}
