#!/usr/bin/env bash
# One-time (per machine) setup for a direct `buck2 build` of Darling.
#
# Two things buck2 cannot work out for itself:
#
#  1. The pinned upstream sources (scripts/buck-src.sh). The working copy is not a
#     complete source tree: 147 trees are nix pins with no checkout.
#  2. The absolute path of Darling's Mach-O linker. clang's `-fuse-ld=` only
#     accepts a linker NAME or an ABSOLUTE path, and a Starlark rule cannot
#     compute the project root, so the path is written into .buckconfig.local
#     (gitignored, machine-local) from the nix store path.
#
# Usage: scripts/buck-setup.sh [--all]     # --all materializes every pinned tree
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
repo_root="$PWD"

want_all=""
[ "${1:-}" = "--all" ] && want_all=1

echo "== pinned sources =="
if [ -n "$want_all" ]; then
	./scripts/buck-src.sh --all
else
	./scripts/buck-src.sh
fi

echo "== Mach-O toolchain =="
ld64="$(nix build "$repo_root#darling-ld64" --no-link --print-out-paths)"
echo "darling-ld64: $ld64"
triplet=x86_64-apple-darwin20
[ -x "$ld64/bin/$triplet-ld" ] || {
	echo "no $triplet-ld in $ld64/bin" >&2
	exit 1
}

# Guest compiles use -nostdinc (the reference build does), which drops clang's
# OWN builtin headers (stddef.h, stdarg.h, ...) along with the host's. The
# reference adds them back with -isystem <resource-dir>/include, so record where
# they are.
clang_resource_dir="$(clang -print-resource-dir)"
echo "clang resource dir: $clang_resource_dir"

# The store path is immutable, so an absolute reference to it is stable; rerun
# this script after bumping the sources that ld64 is built from.
cat >.buckconfig.local <<EOF
# GENERATED by scripts/buck-setup.sh -- machine-local, gitignored.
#
# Absolute paths to prebuilt tools and toolchain dirs the Buck2 build drives.
# The nix ones are store paths (immutable), so this file only needs regenerating
# when the derivation that produces them changes.
[darling]
ld = $ld64/bin/$triplet-ld
ld64_dir = $ld64/bin
clang_resource_dir = $clang_resource_dir
EOF

echo "wrote .buckconfig.local:"
sed 's/^/  /' .buckconfig.local

echo
echo "ready: buck2 build //src/external/darlingserver/duct-tape:darlingserver_duct_tape"
