#!/usr/bin/env bash
# One-time (per machine) setup for a direct `buck2 build` of Darling.
#
# Two things buck2 cannot work out for itself:
#
#  1. The pinned upstream sources (scripts/buck-src.sh). The working copy is not a
#     complete source tree: 147 trees are nix pins with no checkout.
#  2. The absolute path of Darling's Mach-O linker. clang's `-fuse-ld=` only
#     accepts a linker NAME or an ABSOLUTE path, and a Starlark rule cannot
#     compute the project root, so the path is written into .buckconfig.local
#     (gitignored, machine-local) from the nix store path.
#
# Usage: scripts/buck-setup.sh [--all]     # --all materializes every pinned tree
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
repo_root="$PWD"

want_all=""
[ "${1:-}" = "--all" ] && want_all=1

echo "== pinned sources =="
if [ -n "$want_all" ]; then
	./scripts/buck-src.sh --all
else
	./scripts/buck-src.sh
fi

echo "== Mach-O toolchain =="
ld64="$(nix build "$repo_root#darling-ld64" --no-link --print-out-paths)"
echo "darling-ld64: $ld64"
triplet=x86_64-apple-darwin20
[ -x "$ld64/bin/$triplet-ld" ] || {
	echo "no $triplet-ld in $ld64/bin" >&2
	exit 1
}

# Guest compiles use -nostdinc (the reference build does), which drops clang's
# OWN builtin headers (stddef.h, stdarg.h, ...) along with the host's. The
# reference adds them back with -isystem <resource-dir>/include, so record where
# they are.
clang_resource_dir="$(clang -print-resource-dir)"
echo "clang resource dir: $clang_resource_dir"

# Darling reaches HOST libraries through libelfloader, and wrapgen builds the Mach-O stub
# for each one by dlopen()ing the real .so at BUILD time to read its dynamic symbol table.
# dlopen goes through the loader's search path, so every such library's directory has to be
# on it: `dlopen("libfuse.so")` fails without this even though the dev shell contains fuse.
#
# One entry per wrap_elf() in the tree: fuse for hdiutil (darling-dmg), and the sixteen
# src/native ones the gui component wraps. Looked up by SONAME against the dev shell's own
# -L directories (NIX_LDFLAGS), because that is the authoritative list of what this shell
# declares. pkg-config is not enough on its own: giflib ships no .pc file at all, and
# globbing /nix/store is worse than either, since several of these libraries have more than
# one version there and a stub generated against the wrong one exports the wrong symbols.
elf_sonames="libfuse.so libfreetype.so libjpeg.so libpng.so libtiff.so libgif.so libEGL.so
libfontconfig.so libX11.so libXext.so libXrandr.so libXcursor.so libxkbfile.so libcairo.so
libdbus-1.so libGL.so libGLU.so"
_ldirs="$(printf '%s\n' $NIX_LDFLAGS | sed -n 's/^-L//p' | sort -u)"
elf_lib_dirs=""
elf_missing=""
for _so in $elf_sonames; do
	_hit=""
	for _d in $_ldirs; do
		[ -e "$_d/$_so" ] && { _hit="$_d"; break; }
	done
	[ -n "$_hit" ] || _hit="$(pkg-config --variable=libdir "${_so#lib}" 2>/dev/null || true)"
	if [ -n "$_hit" ]; then
		case ":$elf_lib_dirs:" in *":$_hit:"*) ;; *) elf_lib_dirs="${elf_lib_dirs:+$elf_lib_dirs:}$_hit" ;; esac
	else
		elf_missing="$elf_missing $_so"
	fi
done
echo "host ELF lib dirs: $(printf '%s' "$elf_lib_dirs" | tr ':' '\n' | wc -l) entries"
[ -n "$elf_missing" ] && echo "WARNING: cannot locate:$elf_missing -- those wrap_elf stubs will not generate" >&2

# The store path is immutable, so an absolute reference to it is stable; rerun
# this script after bumping the sources that ld64 is built from.
cat >.buckconfig.local <<EOF
# GENERATED by scripts/buck-setup.sh -- machine-local, gitignored.
#
# Absolute paths to prebuilt tools and toolchain dirs the Buck2 build drives.
# The nix ones are store paths (immutable), so this file only needs regenerating
# when the derivation that produces them changes.
[darling]
ld = $ld64/bin/$triplet-ld
ld64_dir = $ld64/bin
clang_resource_dir = $clang_resource_dir
elf_lib_dirs = $elf_lib_dirs
EOF

echo "wrote .buckconfig.local:"
sed 's/^/  /' .buckconfig.local

echo
echo "ready: buck2 build //src/external/darlingserver/duct-tape:darlingserver_duct_tape"
