#!/usr/bin/env python3
"""Emit the Rust half of xnu-sys/src/traps.c from the generated RPC header (#71).

traps.c is 29 lines of source and 35 exported symbols, because its last line is
`DSERVER_DTAPE_DEFS`, an object-like macro that the RPC wrapper generator writes into
ciderd/rpc.internal.h and that expands to 29 more function DEFINITIONS. Each one packs
its scalar arguments into an XNU trap-args struct and calls the trap:

    int dtape_mach_port_deallocate(uint32_t target, uint32_t name) {
        struct _kernelrpc_mach_port_deallocate_args args = {
            .target = target,
            .name = name,
        };
        return _kernelrpc_mach_port_deallocate_trap(&args);
    };

bindgen binds no macros, so this is the one blocker in the file, and it is the reason traps.c
sat at the top of the ranking for weeks looking free. Writing those 29 wrappers by hand would
be transcribing 29 signatures and about 90 field assignments, which is exactly the kind of
thing that goes wrong quietly: a swapped field between two same-typed arguments compiles, links
and returns the wrong answer.

SO THEY ARE GENERATED FROM THE SAME PLACE THE C GETS THEM. This parses the expansion of
DSERVER_DTAPE_DEFS out of the built header, so the Rust and the C are two renderings of one
table. If the RPC generator adds a call, re-running this adds the wrapper.

The output is checked in rather than built by a genrule, matching buck/generated/
duct_tape_flags.bzl, and --check re-derives it and fails if the committed file has drifted.

Usage:
  scripts/gen-dtape-traps.py             # write linux/server/src/xnu/traps_generated.rs
  scripts/gen-dtape-traps.py --check     # fail if the committed file is out of date
"""

import argparse
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "linux/server/src/xnu/traps_generated.rs")

# C scalar types the RPC generator emits, mapped to what bindgen calls them in Rust.
# A type NOT in this table is an error rather than a guess: silently mapping an unknown type is
# how an ABI mismatch gets in.
CTYPE = {
    "uint64_t": "u64",
    "uint32_t": "u32",
    "uint16_t": "u16",
    "uint8_t": "u8",
    "int64_t": "i64",
    "int32_t": "i32",
    "int16_t": "i16",
    "int8_t": "i8",
    "int": "::std::os::raw::c_int",
    "unsigned int": "::std::os::raw::c_uint",
    # C _Bool and Rust bool are both one byte, and bindgen maps the C one to the Rust one.
    "bool": "bool",
}


def header_path():
    hits = glob.glob(os.path.join(
        ROOT, "buck-out/v2/art/root/*/src/external/ciderd/__dserver_rpc__/"
              "*gen_include/ciderd/rpc.internal.h"))
    if not hits:
        sys.exit("rpc.internal.h not built; run: buck2 build //src/external/ciderd:dserver_rpc")
    return hits[0]


def parse(header):
    """Every wrapper in DSERVER_DTAPE_DEFS, as (name, params, struct, fields, trap)."""
    text = open(header).read()
    m = re.search(r"#define DSERVER_DTAPE_DEFS \\\n(.*?)\n\n", text, re.S)
    if not m:
        sys.exit("DSERVER_DTAPE_DEFS not found in the header; did the generator change?")
    body = m.group(1).replace("\\\n", "\n")

    out = []
    for fn in re.findall(r"\tint dtape_(\w+)\((.*?)\)\s*\{\s*"
                         r"struct (\w+) args = \{(.*?)\};\s*"
                         r"return (\w+)\(&args\);", body, re.S):
        name, raw_params, struct, raw_fields, trap = fn
        params = []
        for p in [x.strip() for x in raw_params.split(",") if x.strip()]:
            pm = re.match(r"^(.*?)\s*(\*?)\s*(\w+)$", p)
            if not pm:
                sys.exit(f"cannot parse parameter {p!r} of dtape_{name}")
            ctype, star, pname = pm.group(1).strip(), pm.group(2), pm.group(3)
            if ctype not in CTYPE:
                sys.exit(f"unknown C type {ctype!r} in dtape_{name}; add it to CTYPE rather "
                         f"than guessing")
            rtype = f"*mut {CTYPE[ctype]}" if star else CTYPE[ctype]
            params.append((pname, rtype))
        fields = re.findall(r"\.(\w+)\s*=\s*(\w+)\s*,", raw_fields)
        out.append((name, params, struct, fields, trap))
    return out


def render(wrappers):
    lines = [
        "//! GENERATED by scripts/gen-dtape-traps.py. Do not edit.",
        "//!",
        "//! The Rust half of `xnu-sys/src/traps.c` (#71): the 29 wrappers that",
        "//! `DSERVER_DTAPE_DEFS` expands to in the C. Each packs its scalar arguments into an",
        "//! XNU trap-args struct and calls the trap.",
        "//!",
        "//! Generated from the SAME table the C uses, the expansion of that macro in the built",
        "//! `ciderd/rpc.internal.h`, so the two cannot disagree. Writing them by hand",
        "//! would mean transcribing 29 signatures and about 90 field assignments, and a swapped",
        "//! field between two same-typed arguments would compile, link and return the wrong",
        "//! answer.",
        "",
        "#![allow(clippy::too_many_arguments)]",
        "",
        "use crate::bindings::*;",
        "",
    ]
    for name, params, struct, fields, trap in wrappers:
        arglist = ", ".join(f"{p}: {t}" for p, t in params)
        lines.append("#[no_mangle]")
        lines.append(f"pub unsafe extern \"C\" fn dtape_{name}({arglist}) "
                     f"-> ::std::os::raw::c_int {{")
        lines.append(f"    let mut args: {struct} = ::std::mem::zeroed();")
        for field, value in fields:
            # `as _` reproduces the C's IMPLICIT conversion, with the target inferred from the
            # field. It is needed: the RPC table declares mach_port_mod_refs right as int32_t
            # while the XNU struct field is mach_port_right_t, a u32. C converts silently, Rust
            # will not, and writing the field type out here would be transcribing it.
            lines.append(f"    args.{field} = {value} as _;")
        lines.append(f"    {trap}(&mut args)")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed file differs from what this would write")
    args = ap.parse_args()

    wrappers = parse(header_path())
    if not wrappers:
        sys.exit("parsed zero wrappers, which cannot be right; the macro shape must have changed")
    text = render(wrappers)

    if args.check:
        if not os.path.exists(OUT):
            sys.exit(f"{OUT} does not exist; run scripts/gen-dtape-traps.py")
        if open(OUT).read() != text:
            sys.exit(f"{OUT} is STALE: the RPC table has moved since it was generated.\n"
                     f"Re-run scripts/gen-dtape-traps.py and commit the result.")
        print(f"traps: {len(wrappers)} wrappers, committed file is up to date")
        return 0

    with open(OUT, "w") as f:
        f.write(text)
    print(f"wrote {OUT}: {len(wrappers)} wrappers, "
          f"{sum(len(w[1]) for w in wrappers)} parameters, "
          f"{sum(len(w[3]) for w in wrappers)} field assignments")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
