#!/usr/bin/env nu

# DERIVE A MINIMAL PREFIX FROM THE GENERATED FULL ONE.
#
# The goal this serves is narrow and worth stating: a Cider prefix that boots, runs bash, and
# can run nix to build things. It is not parity. Everything the full prefix installs for GUI,
# ObjC frameworks and scripting languages is dead weight for that, and it is most of the build:
#
#   darwin/frameworks          8,142 actions   29.5% of the graph
#   darwin/private-frameworks  2,250 actions    8.2%
#   perl python pyobjc ruby    1,197 actions    4.3%
#
# buck/prefix/BUCK is GENERATED from the reference build cmake manifests by
# cider-install-from-manifests, so it is not edited by hand and neither is its minimal
# sibling. This reads it, drops the entries whose target lives in an excluded package, drops the
# symlinks those entries orphan, and writes buck/prefix-min/BUCK.
#
# PORTED FROM PYTHON (#98), and the committed buck/prefix-min/BUCK is regenerated BYTE FOR BYTE.
#
# THE FOUR EXCLUSION TABLES WERE NOT RETYPED. They are 130 values across four lists, and hand
# copying them is exactly where a silent one-character error would live, so they were emitted
# mechanically from the python literals with their comments kept, and then checked by dumping
# both sides to JSON and diffing: 8, 101, 6 and 15 values, equal.

const EXCLUDE_PKGS = [
    "//darwin/frameworks"
    "//darwin/private-frameworks"
    "//buck-src/python"
    "//buck-src/python_modules"
    "//buck-src/pyobjc"
    "//buck-src/perl"
    "//buck-src/ruby"
    # zsh's 35 loadable modules. Removing the zsh BINARY by label left these installed at
    # usr/lib/zsh/5.7.1/zsh/*.so, orphaned: nothing can load them. This is also the omission
    # PLAN.md recorded from the start, that the prose claimed the scripting languages were
    # excluded while the list omitted //buck-src/zsh. Closed at the package level.
    "//buck-src/zsh"
]

const EXCLUDE_LABELS = [
    # The swift and swiftc launchers, which select a toolchain that is not installed. Same
    # reasoning as the runtime dylibs under EXCLUDE_DEST: nix does not need Swift to start.
    "//darwin/xcselect:swift_shim"
    "//darwin/xcselect:swiftc_shim"

    "//buck-src:jsc"

    # Userland tools nix can FETCH once it runs. The prefix exists to get nix up; anything
    # nix could install afterwards is being paid for twice, once here and once in the store.
    # None of these participates in booting the container or in running bash.
    #
    # Editors, pagers, shells other than bash, terminal multiplexers.
    "//buck-src:vim"
    "//buck-src:nano"
    "//buck-src:less"
    "//buck-src:tcsh"
    "//buck-src:zsh"
    "//buck-src:ash"
    "//buck-src/screen:screen"
    # Archivers and compressors.
    "//buck-src:gnutar"
    "//buck-src:zip"
    "//buck-src:unzip"
    "//buck-src:unzipsfx"
    "//buck-src:xz"
    "//buck-src:pax"
    # Network clients and daemons.
    "//buck-src:sshd"
    "//buck-src:rsync"
    "//buck-src:netstat"
    "//buck-src:cupsd"
    # Misc userland.
    "//buck-src:top"
    "//buck-src:mail"
    "//buck-src:patch"
    "//buck-src/file:file"
    "//buck-src:otool"
    "//buck-src:hdiutil"
    "//buck-src:installer"
    "//buck-src/groff:eqn"
    "//buck-src:cal"
    "//buck-src:ncal"
    "//buck-src:latency"
    "//buck-src:sc_usage"

    # The GUI cone, reached through three small tools. pbcopy, pbpaste and open are the ONLY
    # prefix entries that reach AppKit or CoreImage (checked by walking every entry's cone),
    # and between them they pull 752 actions of framework into a prefix defined as having no
    # GUI frameworks. Same shape as jsc: a small tool carrying a large cone.
    "//darwin/pboard:pbcopy"
    "//darwin/pboard:pbpaste"
    "//darwin/tools:open"

    # The SUPERSEDED libcrypto/libssl/libtls versions. Darling ships five libcrypto builds for
    # binary compatibility with guest software linking a specific versioned dylib. Only
    # crypto44 has real consumers -- curl_dylib, curlexe, openssl, scp, sftp -- and the other
    # four are self-contained islands, each linked solely by its own ssl/tls sibling:
    #   crypto098 505 + ssl098 44                = 549
    #   crypto35  543 + ssl35  43 + tls6      6  = 592
    #   crypto41  544 + ssl43  38 + tls15    10  = 592
    #   crypto42  539 + ssl44  38 + tls16    10  = 587
    # 2,320 actions for versions nothing in this prefix links. nix carries its own openssl in
    # its store closure, so it needs none of them; the system curl needs crypto44/ssl46/tls18,
    # which stay.
    "//buck-src:crypto098_dylib"
    "//buck-src:ssl098_dylib"
    "//buck-src:crypto35_dylib"
    "//buck-src:ssl35_dylib"
    "//buck-src:tls6_dylib"
    "//buck-src:crypto41_dylib"
    "//buck-src:ssl43_dylib"
    "//buck-src:tls15_dylib"
    "//buck-src:crypto42_dylib"
    "//buck-src:ssl44_dylib"
    "//buck-src:tls16_dylib"

    # The security DAEMONS and the security CLI. Together about 1,390 actions: secd alone is
    # 738 exclusive and additionally pulls CloudKit 257 and AppleAccount 235, and with
    # securitytool it pulls SecurityFoundation 161.
    #
    # The question is not what nix NEEDS, it is what nix needs TO START; once installed it
    # pulls anything else from nixpkgs. Read tests/nix-in-cider.nix for what the guest
    # actually does: the HOST downloads and extracts the installer tarball and copies it in,
    # then the guest runs `bash -x install --no-daemon` followed by nix --version,
    # nix-instantiate --eval, nix eval, nix-store --verify and a trivial derivation. NONE of
    # that does network I/O, so there is no TLS, no trust evaluation and no keychain on the
    # bootstrap path.
    #
    # This cannot regress anything currently verified, and that is checkable rather than
    # hopeful: nix-in-cider runs against the cmake-built FULL `cider`, not this prefix, so
    # no existing test exercises nix here. And Security.framework itself is ALREADY absent from
    # this prefix (0 entries reach Security_dylib; it lives under System/Library/Frameworks,
    # which EXCLUDE_DEST drops), so if nix needed it the minimal prefix was already unable to
    # run nix, independently of these four.
    #
    # If nix-in-guest is ever pointed at this prefix and turns out to need Security, the fix is
    # the Security DYLIB, which is a different and much smaller thing than these daemons.
    "//buck-src:secd"
    "//buck-src:securityd_exe"
    "//buck-src:trustd"
    "//buck-src:securitytool_macos"

    # The OpenSSH suite, and with it openbsd_compat (82 actions, reached by nothing else).
    "//buck-src:ssh"
    "//buck-src:scp"
    "//buck-src:sftp"
    "//buck-src:sftp-server"
    "//buck-src:ssh-add"
    "//buck-src:ssh-agent"
    "//buck-src:ssh-keygen"
    "//buck-src:ssh-keyscan"
    "//buck-src:ssh-keysign"
    "//buck-src:ssh-pkcs11-helper"
    "//buck-src:sshd-keygen-wrapper"

    # curl, openssl and the LAST libcrypto. Keeping crypto44 was justified earlier by "curl
    # needs it", which was the wrong question: the bootstrap does no network I/O, so CURL is
    # not needed either, and the whole chain goes. crypto44_obj alone is 543 actions, the
    # single largest item left in the prefix, plus curl_obj 135.
    "//buck-src:curlexe"
    "//buck-src:curl_dylib"
    "//buck-src:openssl"
    "//buck-src:crypto44_dylib"
    "//buck-src:ssl46_dylib"
    "//buck-src:tls18_dylib"

    # The Berkeley DB command line tools: 225 actions of berkeley_db_obj reached by these
    # twelve and nothing else.
    "//buck-src:db_archive"
    "//buck-src:db_checkpoint"
    "//buck-src:db_codegen"
    "//buck-src:db_deadlock"
    "//buck-src:db_dump"
    "//buck-src:db_hotbackup"
    "//buck-src:db_load"
    "//buck-src:db_printlog"
    "//buck-src:db_recover"
    "//buck-src:db_stat"
    "//buck-src:db_upgrade"
    "//buck-src:db_verify"

    # The BIND DNS diagnostic tools: bind9_dns_obj 84 and bind9_isc_obj 82 are reached by
    # these six and nothing else. Resolution itself is libnetwork/libc, not these.
    "//buck-src:dig"
    "//buck-src:host"
    "//buck-src:nslookup"
    "//buck-src:nsupdate"
    "//buck-src:delv"
    "//buck-src:ddns-confgen"

    # libarchive's tools (archive_obj 115) and the Apache Portable Runtime (apr_obj 82).
    # I flagged these as a residual risk on the grounds that the nix installer might shell out
    # to tar. It does not, and the evidence was already in tests/nix-in-cider.nix when I
    # wrote that: EVERY extraction step is on the HOST. The host curls the tarball, the host
    # runs `tar -xf`, the host `cp -a`s the extracted directory into the prefix, and the guest
    # then runs `install --no-daemon` over plain files. That installer copies $self/store into
    # /nix/store with `cp -RPp` and loads the DB from .reginfo; there is no archive left to
    # unpack guest-side. No tar is needed in the guest.
    "//buck-src:bsdtar"
    "//buck-src:cpio"
    # and libarchive itself, which after those two is installed for its own sake
    # with nothing left consuming it.
    "//buck-src:archive_dylib"
    "//buck-src:apr_dylib"
    "//buck-src:aprutil_dylib"

    # The ncurses ADD-ON libraries. libform, libmenu and libpanel are the form, menu and
    # panel toolkits; their consumers were vim, less, top and screen, all removed. ncurses
    # itself stays, since 60-odd entries still reach it.
    "//buck-src:form_dylib"
    "//buck-src:menu_dylib"
    "//buck-src:panel_dylib"

    # launchd plists whose Program no longer exists, orphaned by the removals above. launchd
    # would try to spawn each of these at boot and fail. THE SMOKE TEST CANNOT CATCH THIS: it
    # runs with DARLING_NO_LAUNCHD=1, so the job graph is never exercised. Found by reading
    # each plist Program/ProgramArguments and checking it against the install destinations.
    "//buck-src:security_OSX_sec_ipc_com.apple.secd.plist"
    "//buck-src:security_securityd_etc_com.apple.securityd.plist"
    "//buck-src:security_trust_trustd_macOS_com.apple.trustd.plist"
    "//buck-src:security_trust_trustd_macOS_com.apple.trustd.agent.plist"
    "//buck-src:openssh_com.openssh.ssh-agent.plist"
    "//buck-src:openssh_com.openssh.sshd.plist"
    "//buck-src:cups_cups_scheduler_org.cups.cupsd.plist"
    # and cups-lpd, whose Program lives under the usr/libexec/cups tree that
    # EXCLUDE_DEST now drops. Caught by buck-prefix-consistency.nu, not by hand.
    "//buck-src:cups_cups_scheduler_org.cups.cups-lpd.plist"
]

const EXCLUDE_SRC = [
    "darwin/frameworks/"
    "darwin/private-frameworks/"
    "buck-src/python"
    "buck-src/pyobjc/"
    "buck-src/perl/"
    "buck-src/ruby/"
]

const EXCLUDE_DEST = [
    "libexec/cider/System/Library/Frameworks/"
    "libexec/cider/System/Library/PrivateFrameworks/"
    "libexec/cider/usr/lib/python"
    "libexec/cider/System/Library/Perl/"

    # Documentation. 810 entries, 44 percent of everything the prefix still installs, and
    # ZERO build actions: they are file copies. They cost prefix SIZE and assembly time, not
    # compile time, and a prefix whose job is to get nix started has no reader for them.
    "libexec/cider/usr/share/man/"

    # DATA ORPHANED BY THE BINARY REMOVALS. Each of these is config or runtime support for a
    # program that is no longer installed, so it is unreachable rather than merely unused.
    # Same class as the dangling symlinks and the launchd plists, just without a reference to
    # make it detectable.
    "libexec/cider/usr/share/cups/",       # cupsd is gone
    "libexec/cider/usr/libexec/cups/",     # 85 actions, the only one of these that compiles
    "libexec/cider/private/etc/cups/"
    "libexec/cider/usr/share/vim/",        # vim is gone
    "libexec/cider/private/etc/ssh/",      # the ssh suite is gone
    "libexec/cider/private/etc/ssl/",      # openssl is gone
    "libexec/cider/usr/share/file/",       # file(1) is gone
    "libexec/cider/usr/lib/sasl2/",        # SASL plugins, for the mail and ssh world
    "libexec/cider/System/Library/Components/",  # the CoreAudio component

    # THE SWIFT RUNTIME, 44 dylibs. Zero build actions, since they are file copies, so this is
    # not a speed removal, it is a correctness one, and it is the safest removal in this file.
    # Every one of those dylibs is a 131-byte GIT LFS POINTER rather than a library (task #39).
    # So a 131-byte text file named libswiftCoreGraphics.dylib is either never loaded, in which
    # case dropping it changes nothing, or it IS loaded and fails, in which case it is already
    # broken. There is no state in which it currently works, so removal cannot regress anything.
    # On the standing criterion it would go anyway: nix does not need Swift to start, and once
    # nix runs it can pull a real Swift from nixpkgs rather than a pointer file.
    "libexec/cider/usr/lib/swift/"
]

def say [msg: string] { print $msg }
def say-err [msg: string] { print -e $msg }

const LABEL_RE = '"\s*:\s*"(//[^"]+)"'
const DEST_RE = '^\s*"([^"]+)"\s*:'
const VALUE_RE = ':\s*"([^"]+)"'

def starts-any [s: string, prefixes: list<string>] {
  $prefixes | any {|p| $s | str starts-with $p }
}

def excluded [line: string] {
  let m = ($line | parse --regex $LABEL_RE)
  if ($m | is-not-empty) {
    let label = ($m | get capture0.0)
    if (starts-any $label $EXCLUDE_PKGS) { return true }
    if ($label in $EXCLUDE_LABELS) { return true }
  }
  let d = ($line | parse --regex $DEST_RE)
  if ($d | is-not-empty) and (starts-any ($d | get capture0.0) $EXCLUDE_DEST) { return true }
  # `files` and `trees` map a destination to a repo-relative SOURCE, not a label.
  if ($m | is-empty) {
    let v = ($line | parse --regex $VALUE_RE)
    if ($v | is-not-empty) and (starts-any ($v | get capture0.0) $EXCLUDE_SRC) { return true }
  }
  false
}

def main [] {
  cd ($env.CURRENT_FILE | path dirname | path join "..")
  let src = "buck/prefix/BUCK"
  if not ($src | path exists) {
    say-err $"no generated prefix at ($src)"
    exit 1
  }
  mkdir buck/prefix-min

  # SPLIT ON \n AND KEEP IT, because the python iterates a file object, so every element still
  # carries its newline and the join is a plain concatenation. Losing that would move every
  # line ending in the output.
  let all = (open --raw $src | decode utf-8 | split row "\n")
  mut kept = []
  mut dropped = 0
  for line in $all {
    if (($line | str trim --left) | str starts-with '"') and (excluded $line) {
      $dropped = $dropped + 1
      continue
    }
    $kept = ($kept | append $line)
  }

  # SECOND PASS: drop symlinks whose target is no longer installed.
  #
  # Removing a binary silently orphans its aliases, because a multi-call binary is shipped once
  # and symlinked under its other names. Dropping `installer` left lsbom, pkgutil and
  # uninstaller pointing at nothing; dropping `less` left `more`; dropping `unzip` left
  # `zipinfo`. Five dangling links, and the prefix would have installed every one of them.
  #
  # That is #41 all over again (eight krb5 .dylib symlinks that dangled), so it is fixed here
  # rather than by naming the five: any future exclusion gets the same treatment for free.
  mut body = ($kept | str join "\n")
  mut installed = []
  for sec in ["entries" "files" "trees"] {
    let re = '(?ms)^\s+' + $sec + ' = \{(.*?)^\s+\},'
    let m = ($body | parse --regex $re)
    if ($m | is-not-empty) {
      $installed = ($installed | append (($m | get capture0.0)
        | parse --regex '(?m)^\s*"([^"]+)"\s*:' | get capture0))
    }
  }
  let installed = ($installed | uniq)

  let sm = ($body | parse --regex '(?ms)^\s+symlinks = \{(.*?)^\s+\},')
  if ($sm | is-not-empty) {
    let orphans = (($sm | get capture0.0) | split row "\n" | where {|line|
      let m = ($line | parse --regex '^\s*"([^"]+)"\s*:\s*"([^"]+)"')
      ($m | is-not-empty) and (not (($m | get capture1.0) in $installed))
    })
    if ($orphans | is-not-empty) {
      # THE TRAILING NEWLINE GOES WITH IT. python iterates splitlines(True), so its `line`
      # still carries the "\n" and removing it removes the whole line; splitting on "\n" here
      # does not, so replacing the text alone left five EMPTY LINES in the output.
      for line in $orphans { $body = ($body | str replace ($line + "\n") "") }
      $dropped = $dropped + ($orphans | length)
      let names = ($orphans | each {|o|
        ($o | parse --regex '^\s*"([^"]+)"' | get capture0.0 | split row "/" | last)
      } | str join ", ")
      say-err $"prefix-min: dropped ($orphans | length) symlink\(s) orphaned by an excluded target: ($names)"
    }
  }
  $body = ($body | str replace 'name = "cider_prefix"' 'name = "cider_prefix_min"')
  let header = ("# GENERATED by scripts/gen-prefix-min.nu from buck/prefix/BUCK -- do not edit.\n"
    + "#\n"
    + "# The full prefix minus the GUI frameworks, the private frameworks and the\n"
    + "# scripting languages. It exists for one purpose: a prefix that boots, runs bash\n"
    + "# and can run nix. Parity lives in //buck/prefix:cider_prefix, which is unchanged.\n"
    + $"# Entries dropped from the full prefix: ($dropped).\n")
  $body = ($body | str replace ("# GENERATED from the reference build's cmake_install.cmake manifests by\n"
    + "# cider-install-from-manifests -- review before committing.\n") $header)

  # THE PATH python PRINTS, which is os.path.join(scripts/.., ...) and keeps the "/.." in it.
  # Cosmetic, and reproduced anyway: the two outputs are compared line for line.
  let dst = "buck/prefix-min/BUCK"
  let dst_printed = (($env.CURRENT_FILE | path dirname) + "/../buck/prefix-min/BUCK")
  $body | save -f $dst

  let total = ($all | where {|l| ($l | str trim --left) | str starts-with '"' } | length)
  say $"prefix-min: dropped ($dropped) of ($total) entries \(((100 * $dropped) // ([$total 1] | math max)) percent), wrote ($dst_printed)"
  if $dropped == 0 {
    say-err "prefix-min: nothing was dropped, the exclusion list is wrong"
    exit 1
  }

  # A generated prefix that REFERS to something it does not install is a defect, and both kinds
  # of reference have already bitten: five symlinks orphaned by removing a multi-call binary,
  # then seven launchd plists whose Program went with the daemon. The symlink half is fixed
  # above by construction; the plist half cannot be, because a plist Program lives in its source
  # file rather than in this BUCK file. So the check runs HERE, and generation fails rather than
  # emitting a prefix someone would only find broken at boot.
  let checker = "scripts/buck-prefix-consistency.nu"
  if ($checker | path exists) {
    let r = (do -i { ^nu $checker --prefix "buck/prefix-min/BUCK" } | complete)
    if $r.exit_code != 0 {
      say-err $r.stdout
      say-err "prefix-min: the generated prefix refers to something it does not install; exclude the referring entry too (see the FAIL lines above)"
      exit 1
    }
  }
  exit 0
}
