#!/usr/bin/env python3
"""Emit mig_gen targets from the reference build.ninja's build-mig edges.

MIG configurations vary more than they look. libsyscall runs mig over the SAME
definition list three times with different suffix sets:

  pass 1  MIG_USER_HEADER_SUFFIX=.h, everything else _unused_*  -> <name>.h
  pass 2  MIG_MULTIARCH="i386 x86_64", suffixes unset (so mig.cmake's defaults
          apply) -> <name>-x86_64-User.c, <name>-i386-User.c, ...
  pass 3  MIG_USER_HEADER_SUFFIX=_internal.h                    -> <name>_internal.h

Rather than re-deriving that from the CMakeLists, this reads the edges: each one
names its defs and its five outputs, so the suffixes follow by subtracting the
stem. Multiarch needs no rule support at all -- the arch infix simply rides in the
suffix (`-x86_64-User.c`).

Usage:
  scripts/gen-mig-from-ninja.py <output-dir-substring> [--prefix NAME] [--deps DEP,...]
"""
from __future__ import annotations

import json
import os
import re
import shlex
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GRAPH = os.path.join(REPO, "result-graph-ref", "build.ninja")
SRC_STORE_RE = re.compile(r"/nix/store/[a-z0-9]{32}-darling-cmake-src")
BIN_DIR = "/build/build"


# Generated mig sources the reference's built libraries CONTAIN but whose compile edge
# does not appear in the graph. libsystem_kernel is the case: `nm -gU` on a cmake-built
# libsystem_kernel.dylib shows _exc_server and _exc_server_routine in __TEXT, which are
# excServer.c's, while the emulation CMakeLists lists only mach_excUser.c and the ninja
# has no excServer.c.o. Without it, anything that binds _exc_server fails to load -- nix's
# boehm-gc does, so guest nix could not start.
EXTRA_COMPILE_SRCS = {
    "emmig_signal_exc": ("signal/excServer.c",),
}


def sdk_env_flags() -> set:
    """The flags //darwin:sdk_env already exports, read from darwin/BUCK.

    Read rather than listed, because the point is to emit the DIFFERENCE: a mig target
    should carry only what its own directory adds on top of the shared Darwin environment.
    Duplicating the shared list here would mean a flag moving into sdk_env silently starts
    appearing twice on every mig command line.
    """
    text = open(os.path.join(REPO, "darwin", "BUCK")).read()
    i = text.find('name = "sdk_env"')
    if i < 0:
        sys.exit("no sdk_env target in darwin/BUCK")
    j = text.index("exported_flags = [", i)
    return set(re.findall(r'"([^"]+)"', text[j:text.index("]", j)]))


def mig_edges(match: str):
    """Yield (defs_repo_path, [output paths], command) for build-mig edges."""
    with open(GRAPH) as f:
        text = f.read()
    cur_head, cur_cmd = None, None
    for line in text.split("\n"):
        if line.startswith("build "):
            cur_head = line[len("build "):].split(": ", 1)[0].split(" | ")[0].split()
            cur_cmd = None
        elif cur_head and line.strip().startswith("COMMAND = ") and "build-mig" in line:
            cur_cmd = line.strip()[len("COMMAND = "):]
            if not any(match in o for o in cur_head):
                continue
            m = re.search(r"(\S+\.defs)\s*(?:;|$)", cur_cmd)
            if not m:
                continue
            defs = SRC_STORE_RE.sub("", m.group(1)).lstrip("/")
            yield defs, cur_head, cur_cmd
            cur_head = None


def main(argv: list[str]) -> int:
    if not os.path.exists(GRAPH):
        sys.exit(f"no reference graph at {GRAPH}")
    args = [a for a in argv[1:] if not a.startswith("--")]
    if not args:
        sys.exit(__doc__)
    match = args[0]
    prefix = "mig"
    if "--prefix" in argv:
        prefix = argv[argv.index("--prefix") + 1]
    deps = ["//darwin:sdk_env"]
    if "--deps" in argv:
        deps = argv[argv.index("--deps") + 1].split(",") + deps

    # The output dir the edges write into is the cmake binary dir; the include
    # paths consumers use are relative to it, so that is the mig out_base.
    seen = set()
    count = 0
    print("# GENERATED by scripts/gen-mig-from-ninja.py -- review before committing.")
    print("#")
    print("# One mig_gen per (definition, pass): the same definitions are run through")
    print("# mig several times with different suffix sets. Multiarch rides in the")
    print("# suffix (-x86_64-User.c), so the rule needs no arch concept of its own.")
    print()
    shared = sdk_env_flags()
    for defs, outs, cmd in mig_edges(match):
        # mig runs the C PREPROCESSOR over the .defs, so a -D the reference passes is not
        # decoration: it decides which routines exist. libsyscall's directory adds
        # PRIVATE=1 on top of the shared Darwin environment, and every `#ifdef PRIVATE`
        # routine in mach_host.defs and friends -- mach_zone_get_zlog_zones,
        # mach_zone_force_gc, host_get_multiuser_config_flags -- is simply ABSENT from
        # libsystem_kernel without it. Nothing fails at build time; the symbol goes missing
        # and the first program to want it fails to link, a long way from here (zlog).
        # LIBSYSCALL_INTERFACE=1 is the same story and appears on only ONE of libsyscall's
        # three passes, which is exactly why these are read per edge rather than assumed.
        # shlex, not split(): the emulation directory passes
        # -DEMULATED_VERSION="Darwin Kernel Version 23.4.0", and a whitespace split turns
        # that one flag into five broken ones.
        try:
            words = shlex.split(cmd)
        except ValueError:
            words = cmd.split()
        migdefs = sorted({
            f for f in words
            if f.startswith("-D") and f not in shared
        })
        # A define whose VALUE carries whitespace or a quote is reported rather than
        # trusted. The emulation directory has several (-DEMULATED_VERSION is a C string
        # literal with spaces in it), and how many levels of quoting survive the trip from
        # cmake through ninja through the shell is not something to guess at: emitted
        # wrong, the macro silently becomes bare tokens instead of a string. The value is
        # still printed, escaped so the Starlark stays valid, with a warning naming it.
        for d in migdefs:
            if any(c in d for c in ' \t"'):
                print(f"WARNING: {defs}: check {d!r} against the reference quoting "
                      f"before committing", file=sys.stderr)
        rel_outs = []
        for o in outs:
            o = o.replace(BIN_DIR, "").lstrip("/")
            if match in o:
                rel_outs.append(o.split(match, 1)[1].lstrip("/"))
        if not rel_outs:
            continue
        stem = os.path.splitext(defs.split(match, 1)[-1].lstrip("/"))[0] if match in defs else \
            os.path.splitext(os.path.basename(defs))[0]
        # Suffix per output = whatever follows the stem.
        suffixes = {}
        for o in rel_outs:
            if not o.startswith(stem):
                continue
            suffix = o[len(stem):]
            if suffix.endswith("Server.h") or suffix.endswith("_server.h"):
                suffixes["sheader"] = suffix
            elif suffix.endswith("Server.c") or suffix.endswith("_server.c"):
                suffixes["server"] = suffix
            elif suffix.endswith("User.c") or suffix.endswith("_user.c"):
                suffixes["user"] = suffix
            elif "xtrace" in suffix.lower():
                suffixes["xtrace"] = suffix
            elif suffix.endswith(".h"):
                suffixes["header"] = suffix
        if len(suffixes) < 3:
            continue
        name = prefix + "_" + re.sub(r"[^A-Za-z0-9]+", "_", stem).strip("_")
        # Distinguish the passes by what the header suffix is.
        tag = ""
        h = suffixes.get("header", "")
        if h and h != ".h":
            tag = "_" + re.sub(r"[^A-Za-z0-9]+", "_", h.rstrip(".h")).strip("_")
        u = suffixes.get("user", "")
        am = re.search(r"-(i386|x86_64)-", u)
        if am:
            tag = "_" + am.group(1)
        full = name + tag
        if full in seen:
            continue
        seen.add(full)
        count += 1
        print("mig_gen(")
        print(f'    name = "{full}",')
        print(f'    defs = "{defs.removeprefix("src/external/")}",')
        # out_base is the directory the OUTPUTS are relative to, not the defs'
        # own directory: consumers include <mach/clock.h>, so the stem has to keep
        # its mach/ prefix.
        base = defs.removeprefix("src/external/")
        base = base[:base.index(match) + len(match)] if match in base else os.path.dirname(base)
        print(f'    out_base = "{base}",')
        for key, attr in (("user", "user_suffix"), ("header", "header_suffix"),
                          ("server", "server_suffix"), ("sheader", "sheader_suffix"),
                          ("xtrace", "xtrace_suffix")):
            if key in suffixes:
                print(f'    {attr} = "{suffixes[key]}",')
        if am:
            print(f'    arch = "{am.group(1)}",')
            # The per-arch User.c is a SOURCE the consumer compiles, so export it.
            print("    compile_srcs = [")
            print(f'        "{stem}{suffixes["user"]}",')
            print("    ],")
        for extra in EXTRA_COMPILE_SRCS.get(full, ()):
            # A generated source the reference BUILD contains but its cli-scope ninja
            # never shows a compile edge for. Kept in one place so regenerating this
            # block does not drop it again.
            print("    compile_srcs = [")
            print(f'        "{extra}",')
            print("    ],")
        if migdefs:
            print("    mig_flags = [")
            for d in migdefs:
                # Escaped, so a value that contains a quote cannot break the file it is
                # pasted into. json.dumps is Starlark-compatible for plain strings.
                print(f"        {json.dumps(d)},")
            print("    ],")
        print('    mig_sh = "//buck-src:mig.sh",')
        print('    migcom = "//buck-src:migcom",')
        print("    deps = [")
        for d in deps:
            print(f'        "{d}",')
        print("    ],")
        print('    visibility = ["PUBLIC"],')
        print(")")
        print()
    print(f"# {count} mig targets", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
