#!/usr/bin/env bash
# install-nix-in-darling.sh — Automated Nix installer for Darling prefixes
#
# This script installs the Nix package manager inside a Darling (macOS
# compatibility layer) prefix, working around the various incompatibilities
# between Darling's environment and the official Nix Darwin installer.
#
# Usage:
#   ./scripts/install-nix-in-darling.sh [OPTIONS]
#
# Options:
#   --prefix <path>       Darling prefix path (default: ~/.darling)
#   --nix-version <ver>   Nix version to install (default: latest stable)
#   --no-channel          Skip channel setup after installation
#   --no-verify           Skip post-install verification
#   --offline             Don't fetch from binary cache (set substitute = false)
#   --help                Show this help message
#
# Prerequisites:
#   - Darling must be installed and `darling shell echo ok` must work
#   - The sandbox-exec stub must be in place (Phase 2)
#   - Syscall fixes from Phase 1 should be applied for full functionality
#
# See: plan/05-phase3-nix-install.md (Task 3.1)

set -euo pipefail

# ── Defaults ────────────────────────────────────────────────────────────────

DARLING_PREFIX="${DPREFIX:-$HOME/.darling}"
NIX_VERSION=""
SETUP_CHANNEL=1
RUN_VERIFY=1
OFFLINE=0
NIX_INSTALL_URL_BASE="https://releases.nixos.org/nix"

# Colors (disabled if not a terminal)
if [ -t 1 ]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[0;33m'
    BLUE='\033[0;34m'
    BOLD='\033[1m'
    RESET='\033[0m'
else
    RED='' GREEN='' YELLOW='' BLUE='' BOLD='' RESET=''
fi

# ── Helpers ─────────────────────────────────────────────────────────────────

log()   { echo -e "${GREEN}[darling-nix]${RESET} $*"; }
warn()  { echo -e "${YELLOW}[darling-nix] WARNING:${RESET} $*" >&2; }
err()   { echo -e "${RED}[darling-nix] ERROR:${RESET} $*" >&2; }
fatal() { err "$@"; exit 1; }

# Run a command inside the Darling prefix
dsh() {
    darling shell "$@"
}

# Run a command inside the Darling prefix with bash -lc (for Nix profile)
dsh_bash() {
    darling shell bash -lc "$*"
}

usage() {
    sed -n '/^# Usage:/,/^# See:/p' "$0" | sed 's/^# \?//'
    exit 0
}

# ── Argument Parsing ────────────────────────────────────────────────────────

while [ $# -gt 0 ]; do
    case "$1" in
        --prefix)
            DARLING_PREFIX="$2"
            shift 2
            ;;
        --nix-version)
            NIX_VERSION="$2"
            shift 2
            ;;
        --no-channel)
            SETUP_CHANNEL=0
            shift
            ;;
        --no-verify)
            RUN_VERIFY=0
            shift
            ;;
        --offline)
            OFFLINE=1
            shift
            ;;
        --help|-h)
            usage
            ;;
        *)
            fatal "Unknown option: $1 (try --help)"
            ;;
    esac
done

# ── Step 0: Prerequisite Checks ────────────────────────────────────────────

log "${BOLD}Step 0: Checking prerequisites...${RESET}"

# Check that darling is installed
if ! command -v darling &>/dev/null; then
    fatal "darling is not installed or not in PATH.\n" \
          "  Install it with: nix build .#darling"
fi

# Check that the prefix exists / can be initialised
if [ ! -d "$DARLING_PREFIX" ]; then
    log "Prefix $DARLING_PREFIX does not exist; initialising..."
    darling shell true 2>/dev/null || true
    sleep 2
fi

if [ ! -d "$DARLING_PREFIX" ]; then
    fatal "Failed to initialise Darling prefix at $DARLING_PREFIX"
fi

# Verify darling shell works
if ! dsh echo ok &>/dev/null; then
    fatal "darling shell is not functional.\n" \
          "  Try: darling shell echo ok"
fi

log "  Darling prefix: $DARLING_PREFIX"
log "  darling shell:  $(dsh sw_vers -productVersion 2>/dev/null || echo 'unknown')"

# Check for sandbox-exec stub (Phase 2)
if ! dsh test -x /usr/bin/sandbox-exec 2>/dev/null; then
    warn "/usr/bin/sandbox-exec not found in Darling prefix."
    warn "Nix builds will fail without it. Install Phase 2 fixes first."
    warn "Continuing anyway (Nix installation may still work)..."
fi

# Check if Nix is already installed
if dsh test -e /nix/store 2>/dev/null; then
    warn "/nix/store already exists in the prefix."
    read -rp "  Reinstall? [y/N] " answer
    if [[ ! "$answer" =~ ^[Yy] ]]; then
        log "Aborted."
        exit 0
    fi
fi

# ── Step 1: Pre-configure Nix ──────────────────────────────────────────────

log "${BOLD}Step 1: Pre-configuring Nix...${RESET}"

dsh mkdir -p /etc/nix

NIX_CONF="# Nix configuration for Darling
# Generated by install-nix-in-darling.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Single-user mode: no build users group needed
build-users-group =

# Disable the macOS sandbox — Darling provides Linux-level isolation
# via namespaces and darlingserver instead.
sandbox = false

# Accept flake commands and the nix3 CLI
experimental-features = nix-command flakes
"

if [ "$OFFLINE" -eq 1 ]; then
    NIX_CONF+="
# Offline mode — no binary substitution
substitute = false
"
else
    NIX_CONF+="
# Binary cache
substituters = https://cache.nixos.org
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
"
fi

# Write via the prefix filesystem directly (more reliable than piping into dsh).
# The directory is created here rather than assumed: a prefix that has never had nix
# in it has no etc/nix, and the redirect then fails before anything useful happens.
mkdir -p "$DARLING_PREFIX/etc/nix"
echo "$NIX_CONF" > "$DARLING_PREFIX/etc/nix/nix.conf"

log "  Wrote /etc/nix/nix.conf"

# ── Step 2: Download the Nix installer ─────────────────────────────────────

log "${BOLD}Step 2: Downloading Nix installer...${RESET}"

# Determine the Nix version to install
if [ -z "$NIX_VERSION" ]; then
    # Fetch the latest stable version from the releases page
    log "  Detecting latest Nix version..."
    NIX_VERSION=$(curl -fsSL https://releases.nixos.org/nix/latest/install 2>/dev/null \
        | grep -oP 'nix-\K[0-9]+\.[0-9]+\.[0-9]+' \
        | head -1 || true)

    if [ -z "$NIX_VERSION" ]; then
        # Fallback: a known-good version
        NIX_VERSION="2.24.12"
        warn "Could not detect latest version, falling back to $NIX_VERSION"
    fi
fi

log "  Nix version: $NIX_VERSION"

INSTALLER_NAME="nix-${NIX_VERSION}-x86_64-darwin"
INSTALLER_URL="${NIX_INSTALL_URL_BASE}/nix-${NIX_VERSION}/${INSTALLER_NAME}.tar.xz"
INSTALLER_HOST_TMP=$(mktemp -d "${TMPDIR:-/tmp}/nix-darling-install.XXXXXX")

cleanup() {
    rm -rf "$INSTALLER_HOST_TMP"
}
trap cleanup EXIT

log "  Downloading $INSTALLER_URL ..."
if ! curl -fSL -o "$INSTALLER_HOST_TMP/installer.tar.xz" "$INSTALLER_URL"; then
    fatal "Failed to download Nix installer.\n" \
          "  URL: $INSTALLER_URL\n" \
          "  Check that the version $NIX_VERSION exists for x86_64-darwin."
fi

log "  Extracting..."
tar -xf "$INSTALLER_HOST_TMP/installer.tar.xz" -C "$INSTALLER_HOST_TMP"

# Find the extracted directory (nix-<version>-x86_64-darwin/)
# -mindepth 1: without it find matches the START directory too, and the temp dir is
# itself called nix-darling-install.XXXXXX -- so `head -1` picked the temp dir, whose
# `install` does not exist, and a perfectly good extraction was reported as a failure.
INSTALLER_DIR=$(find "$INSTALLER_HOST_TMP" -mindepth 1 -maxdepth 1 -type d -name 'nix-*' | head -1)
if [ -z "$INSTALLER_DIR" ] || [ ! -f "$INSTALLER_DIR/install" ]; then
    fatal "Installer extraction failed — cannot find install script."
fi

log "  Installer extracted to: $INSTALLER_DIR"

# ── Step 3: Patch the installer ────────────────────────────────────────────

log "${BOLD}Step 3: Patching installer for Darling compatibility...${RESET}"

INSTALL_SCRIPT="$INSTALLER_DIR/install"

# Count patches applied for reporting
PATCHES=0

# Patch 1: Remove the multi-user enforcement on Darwin.
# The installer detects `uname -s` == Darwin and forces multi-user mode.
# We need single-user (--no-daemon) mode since Directory Services aren't
# available yet.
if grep -q 'case "$(uname -s)"' "$INSTALL_SCRIPT" 2>/dev/null || \
   grep -q 'Darwin' "$INSTALL_SCRIPT" 2>/dev/null; then

    # The typical pattern is:
    #   if [ "$(uname -s)" = "Darwin" ]; then
    #     INSTALL_MODE=daemon
    # We replace forced daemon mode with no-daemon.
    sed -i.bak \
        -e 's/INSTALL_MODE=daemon/INSTALL_MODE=no-daemon/g' \
        "$INSTALL_SCRIPT"
    PATCHES=$((PATCHES + 1))
fi

# Patch 2: Remove diskutil dependency.
# The installer calls `diskutil info /` or `/usr/sbin/diskutil info -plist /`
# to detect APFS. Our diskutil stub now handles this, but if the installer
# does something more complex, this sed catches it.
if grep -q 'diskutil' "$INSTALL_SCRIPT" 2>/dev/null; then
    # Don't actually remove diskutil calls — our stub handles them.
    # But if the installer does `type diskutil` or `command -v diskutil`
    # as a gate, make sure it passes.
    log "  diskutil references found — our stub should handle them"
fi

# Patch 3: Remove xmllint dependency checks.
# If the installer hard-requires xmllint, stub the check.
if grep -q 'xmllint' "$INSTALL_SCRIPT" 2>/dev/null; then
    sed -i.bak \
        -e '/xmllint/d' \
        "$INSTALL_SCRIPT"
    PATCHES=$((PATCHES + 1))
fi

# Patch 4: Remove or relax the root-user check.
# On Darwin the installer may refuse to run as root in certain modes.
# Inside Darling we always run as root.
if grep -q 'running as root is not supported' "$INSTALL_SCRIPT" 2>/dev/null || \
   grep -q 'do not run this script as root' "$INSTALL_SCRIPT" 2>/dev/null; then
    sed -i.bak \
        -e '/running as root is not supported/d' \
        -e '/do not run this script as root/d' \
        "$INSTALL_SCRIPT"
    PATCHES=$((PATCHES + 1))
fi

# Patch 5: Remove dseditgroup / sysadminctl calls (multi-user user creation).
# These should already be unreachable with INSTALL_MODE=no-daemon, but
# belt-and-suspenders.
if grep -q 'dseditgroup\|sysadminctl' "$INSTALL_SCRIPT" 2>/dev/null; then
    log "  Directory Services references found — should be skipped in no-daemon mode"
fi

# Patch 6: Ensure --no-daemon is respected even if the script tries to
# override it for Darwin.
if grep -q 'NIX_INSTALLER_NO_MODIFY_PROFILE' "$INSTALL_SCRIPT" 2>/dev/null; then
    log "  Standard Nix installer detected"
fi

log "  Applied $PATCHES patches to installer script"

# ── Step 4: Copy installer into the Darling prefix and run it ──────────────

log "${BOLD}Step 4: Installing Nix inside Darling...${RESET}"

# Copy the installer into the prefix's /tmp
DARLING_TMP="$DARLING_PREFIX/private/tmp"
mkdir -p "$DARLING_TMP"
DARLING_INSTALLER_DIR="$DARLING_TMP/nix-installer"
rm -rf "$DARLING_INSTALLER_DIR"
cp -a "$INSTALLER_DIR" "$DARLING_INSTALLER_DIR"

# Create /nix in the prefix if it doesn't exist
dsh mkdir -p /nix

# Ensure the install script is executable
chmod +x "$DARLING_INSTALLER_DIR/install"

# Run the patched installer inside Darling
# We use --no-daemon explicitly and set NIX_INSTALLER_NO_MODIFY_PROFILE=1
# to prevent it from modifying shell profiles (we'll handle that ourselves).
log "  Running Nix installer (this may take a few minutes)..."
if ! dsh env \
    NIX_INSTALLER_NO_MODIFY_PROFILE=0 \
    bash -ex /tmp/nix-installer/install --no-daemon 2>&1 | \
    tee "$INSTALLER_HOST_TMP/install.log"; then

    err "Nix installer failed. Log saved to: $INSTALLER_HOST_TMP/install.log"
    err ""
    err "Common causes:"
    err "  - Missing syscall fixes (Phase 1): check for 'Unimplemented syscall' in the log"
    err "  - Missing sandbox-exec (Phase 2): check for 'Bad file descriptor'"
    err "  - Installer script incompatibility: the patches may need updating"
    err ""
    err "Debug tips:"
    err "  strace -f -p \$(pidof darlingserver) -e trace=openat,stat 2>&1 | head -200"
    err "  DARLING_XTRACE=1 darling shell ..."

    # Don't clean up the temp dir on failure so the user can inspect
    trap - EXIT
    fatal "Installation failed. Temp files preserved at: $INSTALLER_HOST_TMP"
fi

log "  ✓ Nix installer completed successfully"

# ── Step 5: Post-install configuration ─────────────────────────────────────

log "${BOLD}Step 5: Post-install configuration...${RESET}"

# Ensure the Nix profile script is sourceable
NIX_PROFILE_SCRIPT="/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh"
NIX_PROFILE_SCRIPT_ALT="/root/.nix-profile/etc/profile.d/nix.sh"

if dsh test -f "$NIX_PROFILE_SCRIPT" 2>/dev/null; then
    log "  Nix profile script: $NIX_PROFILE_SCRIPT"
elif dsh test -f "$NIX_PROFILE_SCRIPT_ALT" 2>/dev/null; then
    NIX_PROFILE_SCRIPT="$NIX_PROFILE_SCRIPT_ALT"
    log "  Nix profile script: $NIX_PROFILE_SCRIPT"
else
    warn "Could not find Nix profile script — Nix may not be on PATH in new shells"
fi

# Ensure /etc/nix/nix.conf wasn't overwritten by the installer
if [ -f "$DARLING_PREFIX/etc/nix/nix.conf" ]; then
    if ! grep -q 'build-users-group =' "$DARLING_PREFIX/etc/nix/nix.conf"; then
        log "  Restoring nix.conf (installer overwrote it)..."
        echo "$NIX_CONF" > "$DARLING_PREFIX/etc/nix/nix.conf"
    fi
fi

# Write a helper profile that sources Nix on login
DARLING_PROFILE_D="$DARLING_PREFIX/etc/profile.d"
mkdir -p "$DARLING_PROFILE_D"
cat > "$DARLING_PROFILE_D/nix-darling.sh" <<'PROFILE'
# Source Nix profile if available
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
    . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
elif [ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then
    . "$HOME/.nix-profile/etc/profile.d/nix.sh"
fi
PROFILE
log "  Wrote /etc/profile.d/nix-darling.sh"

# ── Step 6: Channel / Registry Setup ───────────────────────────────────────

if [ "$SETUP_CHANNEL" -eq 1 ] && [ "$OFFLINE" -eq 0 ]; then
    log "${BOLD}Step 6: Setting up Nix channels...${RESET}"

    if dsh_bash "nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs" 2>/dev/null; then
        log "  Added nixpkgs-unstable channel"

        log "  Updating channels (this downloads ~20 MB)..."
        if dsh_bash "nix-channel --update" 2>/dev/null; then
            log "  ✓ Channels updated"
        else
            warn "Channel update failed — this exercises curl/TLS, which may have issues."
            warn "You can retry later with: darling shell nix-channel --update"
        fi
    else
        warn "Failed to add channel — Nix may not be on PATH yet."
        warn "Try: darling shell bash -lc 'nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs'"
    fi
else
    log "${BOLD}Step 6: Skipping channel setup${RESET} (--no-channel or --offline)"
fi

# ── Step 7: Verification ───────────────────────────────────────────────────

if [ "$RUN_VERIFY" -eq 1 ]; then
    log "${BOLD}Step 7: Verifying installation...${RESET}"

    PASS=0
    FAIL=0

    check() {
        local desc="$1"
        shift
        if "$@" &>/dev/null; then
            log "  ${GREEN}✓${RESET} $desc"
            PASS=$((PASS + 1))
        else
            err "  ✗ $desc"
            FAIL=$((FAIL + 1))
        fi
    }

    check "nix --version" \
        dsh_bash "nix --version"

    check "nix-env --version" \
        dsh_bash "nix-env --version"

    check "nix-store --verify (may take a moment)" \
        dsh_bash "nix-store --verify --no-build 2>/dev/null || nix-store --verify"

    check "nix-instantiate --eval -E '1 + 1'" \
        dsh_bash "nix-instantiate --eval -E '1 + 1'"

    check "nix eval --expr '1 + 1'" \
        dsh_bash "nix eval --expr '1 + 1'"

    check "builtins.currentSystem == x86_64-darwin" \
        dsh_bash "test \"\$(nix eval --expr 'builtins.currentSystem' --raw)\" = 'x86_64-darwin'"

    if [ "$OFFLINE" -eq 0 ]; then
        check "curl to cache.nixos.org" \
            dsh bash -c "curl -sfI https://cache.nixos.org/nix-cache-info >/dev/null 2>&1"
    fi

    echo ""
    log "Verification: ${GREEN}$PASS passed${RESET}, ${RED}$FAIL failed${RESET}"

    if [ "$FAIL" -gt 0 ]; then
        warn "Some checks failed. Nix may be partially functional."
        warn "See plan/05-phase3-nix-install.md for debugging tips."
    fi
else
    log "${BOLD}Step 7: Skipping verification${RESET} (--no-verify)"
fi

# ── Step 8: Clean up ───────────────────────────────────────────────────────

log "${BOLD}Step 8: Cleaning up...${RESET}"

# Remove the installer from the prefix
rm -rf "$DARLING_INSTALLER_DIR"
log "  Removed installer files from prefix"

# ── Done ────────────────────────────────────────────────────────────────────

echo ""
log "${BOLD}${GREEN}═══════════════════════════════════════════════════════${RESET}"
log "${BOLD}${GREEN}  Nix installation inside Darling is complete!${RESET}"
log "${BOLD}${GREEN}═══════════════════════════════════════════════════════${RESET}"
echo ""
log "Nix version: $(dsh_bash 'nix --version' 2>/dev/null || echo 'unknown')"
log "Prefix:      $DARLING_PREFIX"
log "Store:       $DARLING_PREFIX/nix/store"
echo ""
log "Quick start:"
log "  ${BLUE}darling shell bash -lc 'nix --version'${RESET}"
log "  ${BLUE}darling shell bash -lc 'nix eval --expr 1+1'${RESET}"
log "  ${BLUE}darling shell bash -lc 'nix-build --expr \"derivation { name = \\\"test\\\"; builder = \\\"/bin/bash\\\"; args = [\\\"-c\\\" \\\"echo ok > \\\\\\\$out\\\"]; system = \\\"x86_64-darwin\\\"; }\"'${RESET}"
echo ""
log "Or use the wrapper script:"
log "  ${BLUE}./scripts/darling-nix nix --version${RESET}"
log "  ${BLUE}./scripts/darling-nix nix eval --expr '1 + 1'${RESET}"
