#!/bin/sh
set +e

if [ "$(whoami)" != "root" ]
then
	echo "Uninstall must be run as root, invoking sudo"
	exec sudo su -c "$0" "$@"
fi

if command -v cider
then
	$(dirname "$0")/shutdown-user.sh
fi

INSTALL_PREFIX="$(dirname "$(dirname "$(which cider)")")"
if [ -d "${INSTALL_PREFIX}/libexec" ]
then
	rm -rf "${INSTALL_PREFIX}/libexec/cider"
	rmdir --ignore-fail-on-non-empty "${INSTALL_PREFIX}/libexec"
fi
rm -f "${INSTALL_PREFIX}/bin/cider"
rm -f "${INSTALL_PREFIX}/bin/ciderd"
rm -f "${INSTALL_PREFIX}/bin/cider-coredump"
find /lib/modules -name cider-mach.ko -delete
echo "Uninstall complete"
