#ifndef _COREVIDEO_CVIMAGEBUFFER_H_
#define _COREVIDEO_CVIMAGEBUFFER_H_

#include <sys/cdefs.h>
#include <CoreVideo/CVBuffer.h>

typedef CVBufferRef CVImageBufferRef;

extern const CFStringRef kCVImageBufferPixelAspectRatioKey;
extern const CFStringRef kCVImageBufferGammaLevelKey;
extern const CFStringRef kCVImageBufferYCbCrMatrixKey;
extern const CFStringRef kCVImageBufferColorPrimariesKey;
extern const CFStringRef kCVImageBufferTransferFunctionKey;

extern CFStringRef const kCVImageBufferPixelAspectRatioHorizontalSpacingKey;
extern CFStringRef const kCVImageBufferPixelAspectRatioVerticalSpacingKey;

extern CFStringRef const kCVImageBufferYCbCrMatrix_ITU_R_709_2;
extern CFStringRef const kCVImageBufferYCbCrMatrix_ITU_R_601_4;
extern CFStringRef const kCVImageBufferYCbCrMatrix_SMPTE_240M_1995;
extern CFStringRef const kCVImageBufferColorPrimaries_ITU_R_709_2;
extern CFStringRef const kCVImageBufferColorPrimaries_EBU_3213;
extern CFStringRef const kCVImageBufferColorPrimaries_SMPTE_C;
extern CFStringRef const kCVImageBufferTransferFunction_ITU_R_709_2;
extern CFStringRef const kCVImageBufferTransferFunction_SMPTE_240M_1995;
extern CFStringRef const kCVImageBufferTransferFunction_UseGamma;

extern CFStringRef const kCVImageBufferYCbCrMatrix_ITU_R_2020;
extern CFStringRef const kCVImageBufferColorPrimaries_ITU_R_2020;
extern CFStringRef const kCVImageBufferTransferFunction_ITU_R_2020;
extern CFStringRef const kCVImageBufferTransferFunction_ITU_R_2100_HLG;
extern CFStringRef const kCVImageBufferTransferFunction_Linear;
extern CFStringRef const kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ;
extern CFStringRef const kCVImageBufferTransferFunction_SMPTE_ST_428_1;
extern CFStringRef const kCVImageBufferTransferFunction_SMPTE_C;
extern CFStringRef const kCVImageBufferCGColorSpaceKey;
extern CFStringRef const kCVImageBufferChromaLocation_Left;
extern CFStringRef const kCVImageBufferChromaLocation_Bottom;
extern CFStringRef const kCVImageBufferChromaLocation_BottomLeft;
extern CFStringRef const kCVImageBufferChromaLocation_Center;
extern CFStringRef const kCVImageBufferChromaLocation_DV420;
extern CFStringRef const kCVImageBufferChromaLocation_Top;
extern CFStringRef const kCVImageBufferChromaLocation_TopLeft;

#endif // _COREVIDEO_CVIMAGEBUFFER_H_
